server:
    port: 8080
spring:
    application:
        name: fp-web
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
feign:
    hystrix:
        enabled: true